### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nanokoko89** [mdjfs/expo-image-multiple-picker#1]
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

It means:
<ImagePicker
      onSave={(assets) => console.log(assets)}
      onCancel={() => console.log("no permissions or user go back")}
    />

is empty
Can you fix that?

**Comment by mdjfs** [comment]
That's so weird.. Actually if you call the ImagePicker works without problems. Can you share me the code where you're using the picker ?

**Comment by mdjfs** [comment]
No response, so I'm gonna to close the issue
