### ISSUE TITLE
Header size

### ISSUE THREAD

**Issue by MalikAlkhateeb** [mdjfs/expo-image-multiple-picker#13]
The header is big, Can I hide it or minimize it?
![image](https://user-images.githubusercontent.com/35898136/211054407-40745849-3185-4adf-a09e-1cc6e9a3719c.png)

**Comment by mdjfs** [comment]
Hey, what's up, do you put on the router the property headerShow false? And also can you show me how do you render the picker ?

**Comment by MalikAlkhateeb** [comment]
Just it,

![image](https://user-images.githubusercontent.com/35898136/211120156-a8251be8-b942-4243-a8ab-d262fed2439a.png)

**Comment by mdjfs** [comment]
Hmm

![image](https://user-images.githubusercontent.com/56895143/211369136-664a017d-afa6-4b59-9b62-75d5d3aa235b.png)

Do you checked this? also can i see the entire render and styles?

**Comment by andygphillips** [comment]
I saw this issue too, I overrode the DefaultHeader (using the theme: header props) and changed the height property of defaultHeaderContainer. You can copy the DefaultHeader function and styles from the component source code.

Thank you for the great component @mdjfs!

**Comment by Senninseyi** [comment]
have your question been answered @MalikAlkhateeb so it can be closed
