### ISSUE TITLE
How do we access assets in custom Header save function?

### ISSUE THREAD

**Issue by heesungjang** [mdjfs/expo-image-multiple-picker#14]
Hi, first of all thank you so much for this great package. I trying to use custom header, but little bit confused here. 

```
interface HeaderData {
  view: Views
  goToAlbum?: () => void
  imagesPicked: number
  multiple: boolean
  picked: boolean
  album?: Album
  noAlbums: boolean
  save?: () => void
}
```

How can i access to current assets like default onSave function? so that i can to somthing within custom header?

thanks in advnace!

**Comment by mdjfs** [comment]
Hello! How are you? Thanks for the feedback !

Calling the void save will fire the onSave function of the picker with the Assets. I don't know why you need know the Assets to build your custom Header. 

Check the WhatsAppHeader in the documentation. I uses props.save in the button and under the hood that calls the onSave function with the actual assets

**Comment by heesungjang** [comment]
@mdjfs Hello! Thanks for the reply. Yes I misunderstood the api. It workign fine! thanks!
