### ISSUE TITLE
Type Video 

### ISSUE THREAD

**Issue by MalikAlkhateeb** [mdjfs/expo-image-multiple-picker#15]
Can I display only videos in the gallery when I select the type as Video?

**Comment by mdjfs** [comment]
Hi Malik! Thanks for your feedback

In this moment we don't have any way to select only videos. But, is a great feature request. I'll be working on that, or if you want make a PR you're welcome

Cheers

**Comment by MalikAlkhateeb** [comment]
Thank u man

**Comment by mdjfs** [comment]
Hi! how it's going?

![image](https://user-images.githubusercontent.com/56895143/213326716-ffe746f5-fa07-41ad-80ca-a2e409bc4cb3.png)

Let me know if that works for you

**Comment by MalikAlkhateeb** [comment]
Unfortunately, not working

**Comment by mdjfs** [comment]
Hey what's up, do you upgrade to the last version? (4.7.8)

**Comment by MalikAlkhateeb** [comment]
![image](https://user-images.githubusercontent.com/35898136/213801984-63528390-1559-4357-b8e8-e530f22afd00.png)
yes

**Comment by mdjfs** [comment]
Weird. I test that yesterday. Can you give me an screenshot calling the picker? I'll test again

**Comment by MalikAlkhateeb** [comment]
sure
![image](https://user-images.githubusercontent.com/35898136/213807270-16403893-2b1a-46fb-b720-422a1144c7f5.png)

**Comment by mdjfs** [comment]
Yeah I see, is image, not images

**Comment by MalikAlkhateeb** [comment]
I'm so sorry, I noticed this now
Thank u man again
