### ISSUE TITLE
[Feature Request] Accept an array of Assets in order to edit

### ISSUE THREAD

**Issue by MrSinaRJ** [mdjfs/expo-image-multiple-picker#3]
**Why**
Right now the only way to edit a user's selected assets is to manually show them and after selection add/remove them to/from the assets array.

**How** (suggestion)
Editing a user's selection requires opening the `<ImagePicker/>` with assets selected so the user can edit the selection. It can be an optional parameter. It can be passed an empty array which can be handled by `useState` so the user has control over the selected assets and pass them to `<ImagePicker/>` as a value like the following:
```
const [content, setContent] = useState([]);

<ImagePicker
      onSave={(assets) => setContent(assets)}
      onCancel={() => console.log('no permissions or user go back')}
      multiple
      selected={content}
/>
```

**Comment by MrSinaRJ** [comment]
Hey man,
Thanks for the update and much-needed enhancement.
I have 2 problems with it:
1. When you open the Image Picker and pass the selected array you will go to the last Album which was open, but when you change Album, it's like "selected" assets won't be shown anymore.
2. You can't select photos from different Albums in one take (I don't know if it existed before or if it's a new thing, I didn't check this before)


It's an amazing repo it can be one of the leading projects in the expo. 
I don't know if you're open to collaboration, but I see some great potential in this awesome library.

**Comment by mdjfs** [comment]
Hi!

You're welcome. Thanks for the feedback!

That's is not a bug, when you go back to select an Album, the assets will be unselected. And is also the reason about why you can't select photos from different Albums in one take. The only way to select photos from different albums right now is use the noAlbums property

That is a great feature. It requires some code but is possible select assets from different albums

Thank's for check this library. The point is the personalization, performance and basic interfaces 

I'm totally open to collaboration. If you want feel free to do a pull request about this new feature required and i'll check it gracefully
