### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNSVGSvgView

### ISSUE THREAD

**Issue by shop-fluencer** [mdjfs/expo-image-multiple-picker#4]
Why I get this err ?

```
Invariant Violation: Tried to register two views with the same name RNSVGSvgView
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
```

**Comment by mdjfs** [comment]
Hi! what version of react-native-svg are you using?

**Comment by tonvlad88** [comment]
> react-native-svg
Hi @mdjfs, I was able to replicate this issue, here is the version "react-native-svg": "12.3.0",

**Comment by mdjfs** [comment]
Hmm yes, if you can give me the context when you are getting this error would be really helpful

I'm thinking about can be more than one react-native-svg installed because this project has react-native-svg as a dependency and not a peer dependency

**Comment by tonvlad88** [comment]
> Hmm yes, if you can give me the context when you are getting this error would be really helpful
> 
> I'm thinking about can be more than one react-native-svg installed because this project has react-native-svg as a dependency and not a peer dependency

Okay, I am not sure what context to be shown but this is what I have in my log, hope it helps.

![image](https://user-images.githubusercontent.com/40188798/200131469-529ff4f4-136b-4a0d-9467-ce256b8030d1.png)
![Screenshot_1667666562](https://user-images.githubusercontent.com/40188798/200131487-cb7e3ca5-91a0-42fa-9f7b-eaf574c3976b.png)

**Comment by mdjfs** [comment]
> > Hmm yes, if you can give me the context when you are getting this error would be really helpful
> > I'm thinking about can be more than one react-native-svg installed because this project has react-native-svg as a dependency and not a peer dependency
> 
> Okay, I am not sure what context to be shown but this is what I have in my log, hope it helps.
> 
> ![image](https://user-images.githubusercontent.com/40188798/200131469-529ff4f4-136b-4a0d-9467-ce256b8030d1.png) ![Screenshot_1667666562](https://user-images.githubusercontent.com/40188798/200131487-cb7e3ca5-91a0-42fa-9f7b-eaf574c3976b.png)

And that's happens when you start the project? Or when you do a specific action

**Comment by tonvlad88** [comment]
> > > Hmm yes, if you can give me the context when you are getting this error would be really helpful
> > > I'm thinking about can be more than one react-native-svg installed because this project has react-native-svg as a dependency and not a peer dependency
> > 
> > 
> > Okay, I am not sure what context to be shown but this is what I have in my log, hope it helps.
> > ![image](https://user-images.githubusercontent.com/40188798/200131469-529ff4f4-136b-4a0d-9467-ce256b8030d1.png) ![Screenshot_1667666562](https://user-images.githubusercontent.com/40188798/200131487-cb7e3ca5-91a0-42fa-9f7b-eaf574c3976b.png)
> 
> And that's happens when you start the project? Or when you do a specific action

When I start the project.

**Comment by mdjfs** [comment]
Hi! Please install the new version `4.6.4` and let me know if the issue persist. Thanks!

**Comment by tonvlad88** [comment]
> Hi! Please install the new version `4.6.4` and let me know if the issue persist. Thanks! @tonvlad88

It worked! Thanks @mdjfs

**Comment by mdjfs** [comment]
Thanks for the feedback and helping to solve the issue!
