### ISSUE TITLE
Enhancement: Limit selection of pictures

### ISSUE THREAD

**Issue by luismiguelamado** [mdjfs/expo-image-multiple-picker#5]
Hi there,
First of all, great image picker. One of the best I ever used. :)

I would like to suggest **adding a prop to limit the number of images selected**. 
Right now, the user can select as many images as they wish.

Thank you for such an amazing picker!

**Comment by mdjfs** [comment]
Hi ! Thanks for the feedback 👍 yeah is a great alternative of native image picker

I like the idea, then i released a new version **4.6.0** and I hope can be useful to you

![image](https://user-images.githubusercontent.com/56895143/198899333-8bb98855-6c34-4c7c-8a5f-81f07d6c579e.png)
