### ISSUE TITLE
Support For expo-media-library

### ISSUE THREAD

**Issue by next6leo** [mdjfs/expo-image-multiple-picker#7]
hi can we support use of expo-media-library Version 12.1.2?

**Comment by mdjfs** [comment]
Hi! The current version for expo-media-library is 15.0.0 (i just realized i put bad the version in the readme.md, will change that). For what reason you need that specific version? Change the 15.0.0 to an older version probably affect the picker and downgrade the performance

**Comment by mdjfs** [comment]
Hi, i just realized maybe you want an older version of expo-media-library because thats depends of your expo version.

Then, i released the 4.7.2 using expo-media-library as a peer dependency, feel free to use the expo-media-library in any version 

Let me know if that works

**Comment by next6leo** [comment]
hi @mdjfs thank you alot, yes yes is working i was able to build my projects already. for the past year i have been serching for multiple upload image in expo. your is the very best thank you alot. i am using bare workflow ejected from managed. i dont know why i force install expo-media-library using 15.0.0. when try run the projects it give me error Execution failed for task ':expo-media-library:compileDebugKotlin'.

**Comment by mdjfs** [comment]
hmmm. Is weird, but well, if works nice with an older version great! I'm very glad to contribute. And also i'm open to new features if them are necessary and easy to do.

Thank you for you feedback! Happy coding
